// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-10-02 11:07:55.842661 +0800 CST m=+0.062199661

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/v1/book/add/short_comment": {
            "post": {
                "description": "新增短评",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "新增短评",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "短评信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/book.AddShortCommentBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/book/detail/{isbn}": {
            "get": {
                "description": "通过 isbn 获取书籍详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "通过 isbn 获取书籍详细信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "书籍的 isbn 号",
                        "name": "isbn",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/book/favor/{book_id}": {
            "get": {
                "description": "获取书籍点赞情况",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "获取书籍点赞情况",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "书籍 id",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/book/favor_count": {
            "get": {
                "description": "获取喜欢书籍数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "获取喜欢书籍数量",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/book/hot_keyword": {
            "get": {
                "description": "获取热搜关键字",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "获取热搜关键字",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/book/hot_list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "获取热门书籍(概要)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.BookSerializer"
                            }
                        }
                    }
                }
            }
        },
        "/v1/book/search": {
            "get": {
                "description": "书籍搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "书籍搜索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索内容,比如你想搜索python相关书籍,则输入python",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "返回完整或简介,默认为0,0为完整内容,1为简介",
                        "name": "summary",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始记录数，默认为0",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "记录条数，默认为20,超过依然按照20条计算",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/book/short_comment/{book_id}": {
            "get": {
                "description": "获取书籍短评",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "获取书籍短评",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "书籍 id",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/classic/detail/{type}/{id}": {
            "get": {
                "description": "获取某一期详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classic"
                ],
                "summary": "获取某一期详细信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "期刊的类型 100 200 300",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前期刊的 id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ClassicSerializer"
                        }
                    }
                }
            }
        },
        "/v1/classic/favor": {
            "get": {
                "description": "获取我喜欢的期刊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classic"
                ],
                "summary": "获取我喜欢的期刊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ClassicSerializer"
                            }
                        }
                    }
                }
            }
        },
        "/v1/classic/favor/{type}/{id}": {
            "get": {
                "description": "获取点赞信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classic"
                ],
                "summary": "获取点赞信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "期刊的类型 100 200 300",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前期刊的 id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/classic/latest": {
            "get": {
                "description": "获取最新一期期刊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classic"
                ],
                "summary": "获取最新一期期刊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ClassicSerializer"
                        }
                    }
                }
            }
        },
        "/v1/classic/next/{index}": {
            "get": {
                "description": "获取当前一期的下一期期刊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classic"
                ],
                "summary": "获取当前一期的下一期期刊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前期刊的 index",
                        "name": "index",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ClassicSerializer"
                        }
                    }
                }
            }
        },
        "/v1/classic/previous/{index}": {
            "get": {
                "description": "获取当前一期的上一期期刊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Classic"
                ],
                "summary": "获取当前一期的上一期期刊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "当前期刊的 index",
                        "name": "index",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ClassicSerializer"
                        }
                    }
                }
            }
        },
        "/v1/like": {
            "post": {
                "description": "进行点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "summary": "进行点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "点赞的信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/like.LikeBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/like/cancel": {
            "post": {
                "description": "取消点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Like"
                ],
                "summary": "取消点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "令牌: 测试可用 admin 或你自己的 appkey",
                        "name": "appkey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "取消点赞的信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/like.LikeBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "get": {
                "description": "获取所有用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取所有用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/user.UserBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "book.AddShortCommentBody": {
            "type": "object",
            "required": [
                "book_id",
                "content"
            ],
            "properties": {
                "book_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "handler.Response": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "integer"
                },
                "error_message": {
                    "type": "string"
                },
                "msg": {
                    "type": "object"
                },
                "request": {
                    "type": "string"
                }
            }
        },
        "like.LikeBody": {
            "type": "object",
            "required": [
                "art_id",
                "type"
            ],
            "properties": {
                "art_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "model.BookSerializer": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "fav_nums": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "like_status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.ClassicSerializer": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "fav_nums": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "like_status": {
                    "type": "integer"
                },
                "pubdate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user.UserBody": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
